#!/usr/bin/env python3
"""Render the mentor /insights-style HTML report — a crafted, self-contained artifact.

Merges deterministic stats (collect.py) with the model's written analysis (the
eight sections) into one HTML file: inline SVG line icons (no emoji), count-up
numbers, animated bars, scroll-reveal that respects prefers-reduced-motion, and
a restrained dark instrument palette. No AI-slop tropes (no side-stripe borders,
no gradient text, no glass, no generic card grid). Prints the output path.

Language: the static chrome is localized (English default, Russian available). Set
it via the analysis's "lang" field ("en" | "ru") or --lang; the model-written
content is in whatever language the analysis was authored in.

Usage:
    uv run --no-project python render_report.py \
        --stats /tmp/mentor-stats.json --analysis /tmp/mentor-analysis.json \
        --out ~/.claude/usage-data/mentor-report.html [--lang en|ru]

analysis.json shape (all optional; missing keys render empty):
{
  "lang": "en",
  "period_label": "last 30 days",
  "summary": "the honest summary, including what is hindering",
  "sections": {
    "what_you_work_on": [{"theme": "...", "detail": "...", "share": "~40%"}],
    "how_you_use":      ["line", ...],
    "impressive":       ["line", ...],
    "friction":         [{"problem": "...", "evidence": "...", "fix": "..."}],
    "features_to_try":  ["line", ...],
    "claude_md_additions": ["line for CLAUDE.md", ...],
    "new_ways":         ["line", ...],
    "on_the_horizon":   "paragraph"
  }
}
"""
import json, sys, os, html

# ── inline SVG line icons (stroke, currentColor) ────────────────────────────
ICONS = {
    "message": '<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>',
    "layers": '<path d="M12 2 2 7l10 5 10-5-10-5Z"/><path d="m2 17 10 5 10-5"/><path d="m2 12 10 5 10-5"/>',
    "calendar": '<rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/>',
    "terminal": '<path d="m4 17 6-6-6-6"/><path d="M12 19h8"/>',
    "edit": '<path d="M12 20h9"/><path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4Z"/>',
    "file": '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6"/>',
    "cpu": '<rect x="4" y="4" width="16" height="16" rx="2"/><rect x="9" y="9" width="6" height="6"/><path d="M9 2v2M15 2v2M9 20v2M15 20v2M2 9h2M2 15h2M20 9h2M20 15h2"/>',
    "gauge": '<path d="m12 14 4-4"/><path d="M3.34 19a10 10 0 1 1 17.32 0"/>',
    "target": '<circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/>',
    "activity": '<path d="M22 12h-4l-3 9L9 3l-3 9H2"/>',
    "award": '<circle cx="12" cy="8" r="6"/><path d="M15.48 12.89 17 22l-5-3-5 3 1.52-9.11"/>',
    "alert": '<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/><path d="M12 9v4M12 17h.01"/>',
    "compass": '<circle cx="12" cy="12" r="10"/><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"/>',
    "filecode": '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6"/><path d="m9 18-2-2 2-2M15 14l2 2-2 2"/>',
    "branch": '<line x1="6" y1="3" x2="6" y2="15"/><circle cx="18" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><path d="M18 9a9 9 0 0 1-9 9"/>',
    "trending": '<polyline points="22 7 13.5 15.5 8.5 10.5 2 17"/><polyline points="16 7 22 7 22 13"/>',
    "bars": '<line x1="12" y1="20" x2="12" y2="10"/><line x1="18" y1="20" x2="18" y2="4"/><line x1="6" y1="20" x2="6" y2="16"/>',
    "cpu2": '<rect x="4" y="4" width="16" height="16" rx="2"/><path d="M9 9h6v6H9z"/>',
    "check": '<path d="M20 6 9 17l-5-5"/>',
}

# ── localized static chrome (English default, Russian available) ────────────
LABELS = {
    "en": {
        "title": "Mentor · session report", "eyebrow": "MENTOR · how you work with agents",
        "h1": "How you work with your agents", "agents": "agents", "models": "models",
        "summary_k": "The honest summary", "by_day": "Activity by day",
        "s_work": "What you work on", "s_use": "How you use the agent", "s_win": "What you did well",
        "s_fric": "Where things go wrong", "s_feat": "Features worth trying",
        "s_md": "Suggested CLAUDE.md additions", "s_new": "New ways to use it", "s_hor": "On the horizon",
        "tools": "Tools", "langs": "Languages (from edited files)", "fix": "Fix.",
        "st_msg": "messages", "st_ses": "sessions", "st_days": "active days", "st_tool": "tool calls",
        "st_edit": "edits", "st_file": "files", "st_tok": "k output tokens", "st_mpd": "messages / day",
        "no_data": "no data", "no_fric": "no notable friction found", "no_sugg": "no suggestions",
        "no_edit": "no file edits", "period": "last {n} days",
        "foot": "Generated by mentor · {ts} · some judgments are model-inferred, read them as hypotheses, not verdicts.",
    },
    "ru": {
        "title": "Mentor · разбор сессий", "eyebrow": "MENTOR · разбор работы с агентами",
        "h1": "Как ты работаешь с агентами", "agents": "агенты", "models": "модели",
        "summary_k": "Итог без прикрас", "by_day": "Активность по дням",
        "s_work": "Над чем ты работаешь", "s_use": "Как ты используешь агента", "s_win": "Что получилось сильно",
        "s_fric": "Где всё идёт не так", "s_feat": "Возможности, которые стоит попробовать",
        "s_md": "Что добавить в CLAUDE.md", "s_new": "Новые способы использования", "s_hor": "Куда двигается твой воркфлоу",
        "tools": "Инструменты", "langs": "Языки (по правкам файлов)", "fix": "Фикс.",
        "st_msg": "сообщений", "st_ses": "сессий", "st_days": "активных дней", "st_tool": "вызовов тулзов",
        "st_edit": "правок", "st_file": "файлов", "st_tok": "тыс. токенов на выход", "st_mpd": "сообщений в день",
        "no_data": "нет данных", "no_fric": "заметного трения не найдено", "no_sugg": "нет предложений",
        "no_edit": "нет правок файлов", "period": "последние {n} дней",
        "foot": "Сгенерировано mentor · {ts} · часть оценок выведена моделью, читай их как гипотезу, а не приговор.",
    },
}


def ic(name, cls="ic"):
    return (f'<svg class="{cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
            f'stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" '
            f'aria-hidden="true">{ICONS.get(name, "")}</svg>')


CSS = """
:root{
  --bg:#1b1a18; --surface:#262420; --surface2:#302d28; --line:#3c3833;
  --ink:#f4efe6; --mut:#bcb4aa; --faint:#847d73;
  --mint:#7fe6d0; --pink:#ff789f; --orange:#ff9a4d; --coral:#ff8163;
  --mono:ui-monospace,"SF Mono",SFMono-Regular,Menlo,Consolas,monospace;
  --sans:system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  --e:cubic-bezier(.16,1,.3,1);
}
*{box-sizing:border-box}
html{scroll-behavior:smooth}
body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);
  font-size:16px;line-height:1.65;-webkit-font-smoothing:antialiased;
  background-image:radial-gradient(900px 420px at 12% -8%,rgba(255,120,159,.045),transparent 60%),
    radial-gradient(1000px 460px at 88% -4%,rgba(127,230,208,.05),transparent 62%)}
.wrap{max-width:860px;margin:0 auto;padding:56px 24px 96px}
a{color:var(--mint)}
.i-mint{color:var(--mint)!important}.i-pink{color:var(--pink)!important}
.i-orange{color:var(--orange)!important}.i-coral{color:var(--coral)!important}

.eyebrow{display:inline-flex;align-items:center;gap:8px;color:var(--mint);
  font-size:13px;font-weight:600;letter-spacing:.03em}
.eyebrow .ic{width:16px;height:16px}
h1{font-size:clamp(30px,5vw,46px);line-height:1.06;letter-spacing:-.03em;
  font-weight:700;margin:14px 0 8px;text-wrap:balance}
.meta{color:var(--faint);font-size:14px;margin:0 0 30px}
.meta b{color:var(--mut);font-weight:600}

.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;
  background:var(--line);border:1px solid var(--line);border-radius:16px;
  overflow:hidden;margin:8px 0 34px}
.stat{background:var(--surface);padding:16px 18px;display:flex;flex-direction:column;gap:6px}
.stat .top{display:flex;align-items:center;gap:8px}
.stat .top .ic{width:16px;height:16px}
.stat .lbl{font-size:12.5px;color:var(--faint)}
.stat .num{font-family:var(--mono);font-size:23px;font-weight:600;letter-spacing:-.02em;
  color:var(--ink);font-variant-numeric:tabular-nums}

.summary{background:linear-gradient(180deg,rgba(120,228,207,.05),rgba(120,228,207,.02));
  border:1px solid rgba(120,228,207,.22);border-radius:16px;padding:22px 24px;margin:0 0 12px}
.summary .k{display:inline-flex;align-items:center;gap:8px;color:var(--mint);
  font-size:13px;font-weight:600;margin-bottom:10px}
.summary .k .ic{width:17px;height:17px}
.summary p{margin:0;color:#e9e4d8;white-space:pre-wrap;max-width:72ch}

section{margin-top:46px}
h2{display:flex;align-items:center;gap:11px;font-size:20px;font-weight:660;
  letter-spacing:-.015em;margin:0 0 16px}
h2 .badge{display:grid;place-items:center;width:34px;height:34px;border-radius:10px;
  background:var(--surface2);border:1px solid var(--line);flex:none}
h2 .badge .ic{width:19px;height:19px}

.chart{background:var(--surface);border:1px solid var(--line);border-radius:16px;padding:20px 22px}
.bars{display:flex;align-items:flex-end;gap:5px;height:104px}
.bar{flex:1;min-width:3px;background:linear-gradient(180deg,var(--pink),var(--orange));
  border-radius:4px 4px 2px 2px;height:var(--h)}
.js .bar{animation:grow .85s var(--e) both}
@keyframes grow{from{height:2px}}
.axis{display:flex;justify-content:space-between;color:var(--faint);font-size:12px;
  margin-top:10px;font-family:var(--mono)}

.chips{display:flex;flex-wrap:wrap;gap:7px;margin:2px 0 6px}
.chip{background:var(--surface);border:1px solid var(--line);border-radius:9px;
  padding:5px 11px;font-size:13px;color:var(--mut);font-family:var(--mono)}
.chip b{color:var(--ink);font-weight:600}
.label{color:var(--faint);font-size:13px;margin:14px 0 6px}

.theme{padding:15px 0;border-bottom:1px solid var(--line);display:flex;gap:16px;align-items:baseline}
.theme:last-child{border-bottom:0}
.theme .share{font-family:var(--mono);color:var(--mint);font-size:13px;min-width:52px;flex:none}
.theme .t{font-weight:640;color:var(--ink)}
.theme .d{color:var(--mut);font-size:14.5px;margin-top:2px;max-width:66ch}

.list{list-style:none;margin:0;padding:0}
.list li{position:relative;padding:9px 0 9px 26px;border-bottom:1px solid var(--line);color:#e4e0d5;max-width:74ch}
.list li:last-child{border-bottom:0}
.list li::before{content:"";position:absolute;left:4px;top:16px;width:7px;height:7px;
  border-radius:50%;background:var(--mint)}

.fr{background:linear-gradient(180deg,rgba(255,122,92,.07),rgba(255,122,92,.03));
  border:1px solid rgba(255,122,92,.24);border-radius:14px;padding:16px 18px;margin:12px 0;
  transition:border-color .2s var(--e)}
.fr:hover{border-color:rgba(255,122,92,.42)}
.fr .head{display:flex;align-items:center;gap:10px;font-weight:660;color:var(--ink)}
.fr .head .ic{width:18px;height:18px;color:var(--coral);flex:none}
.fr .ev{color:var(--mut);font-size:14px;margin:8px 0 12px 28px;max-width:70ch}
.fr .fix{display:flex;gap:9px;align-items:flex-start;margin-left:28px;color:var(--ink);
  background:rgba(127,230,208,.15);border:1px solid rgba(127,230,208,.5);border-radius:10px;
  padding:11px 14px;box-shadow:0 8px 26px -14px rgba(127,230,208,.55)}
.fr .fix .ic{width:16px;height:16px;color:var(--mint);margin-top:3px;flex:none}
.fr .fix b{color:var(--mint);font-weight:700}

pre{background:#120d0a;border:1px solid rgba(127,230,208,.32);border-radius:12px;padding:16px 18px;
  overflow:auto;font-family:var(--mono);font-size:13.5px;line-height:1.7;color:#a9f0dc;margin:0;
  box-shadow:0 8px 26px -16px rgba(127,230,208,.42)}

.horizon{background:linear-gradient(180deg,rgba(255,145,66,.06),rgba(255,145,66,.02));
  border:1px solid rgba(255,145,66,.22);border-radius:16px;padding:20px 22px;color:#e9e4d8;max-width:74ch}
.mut{color:var(--faint)}
.foot{margin-top:52px;padding-top:18px;border-top:1px solid var(--line);
  color:var(--faint);font-size:12.5px;display:flex;align-items:center;gap:8px}
.foot .ic{width:15px;height:15px;color:var(--mint)}

.js .reveal{opacity:0;transform:translateY(16px);transition:opacity .6s var(--e),transform .6s var(--e)}
.js .reveal.in{opacity:1;transform:none}
@media (prefers-reduced-motion:reduce){
  html{scroll-behavior:auto}
  .js .reveal{opacity:1!important;transform:none!important;transition:none}
  .js .bar{animation:none}
  .fr{transition:none}
}
@media(max-width:640px){.stats{grid-template-columns:repeat(2,1fr)}}
@media(max-width:520px){.wrap{padding:40px 16px 72px}.theme{flex-direction:column;gap:4px}}
"""

JS = """
document.documentElement.classList.add('js');
const rm = matchMedia('(prefers-reduced-motion:reduce)').matches;
const loc = document.documentElement.lang === 'ru' ? 'ru-RU' : 'en-US';
const io = new IntersectionObserver((es)=>{es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target);}})},{threshold:.12});
document.querySelectorAll('.reveal,.chart').forEach(el=>io.observe(el));
function fmt(n,dec){return dec?n.toFixed(dec):Math.round(n).toLocaleString(loc);}
function countUp(el){
  const to=+el.dataset.to, dec=+(el.dataset.dec||0), suf=el.dataset.suf||'';
  if(rm){el.textContent=fmt(to,dec)+suf;return;}
  const t0=performance.now(), dur=1100;
  function step(t){let p=Math.min(1,(t-t0)/dur);p=1-Math.pow(1-p,4);
    el.textContent=fmt(to*p,dec)+suf;if(p<1)requestAnimationFrame(step);}
  requestAnimationFrame(step);
}
const numObs=new IntersectionObserver((es)=>{es.forEach(e=>{if(e.isIntersecting){countUp(e.target);numObs.unobserve(e.target);}})},{threshold:1});
document.querySelectorAll('.num[data-to]').forEach(el=>numObs.observe(el));
"""


def esc(x):
    return html.escape(str(x if x is not None else ""))


def stat(icon, num, label, color="mint"):
    return (f'<div class="stat"><div class="top">{ic(icon, f"ic i-{color}")}<span class="lbl">{esc(label)}</span></div>'
            f'<div class="num" data-to="{num}" data-dec="0" data-suf="">{num:,.0f}</div></div>')


def stat_suf(icon, num, label, suf, color="mint"):
    return (f'<div class="stat"><div class="top">{ic(icon, f"ic i-{color}")}<span class="lbl">{esc(label)}</span></div>'
            f'<div class="num" data-to="{num}" data-dec="0" data-suf="{esc(suf)}">{num:,.0f}{esc(suf)}</div></div>')


def h2(icon, title, color="mint"):
    return f'<h2><span class="badge">{ic(icon, f"ic i-{color}")}</span>{esc(title)}</h2>'


def per_day(pd, L):
    items = [(k, v) for k, v in pd.items() if k != "?"]
    if not items:
        return ""
    mx = max(v for _, v in items) or 1
    bars = "".join(f'<div class="bar" style="--h:{max(3,int(v/mx*100))}%" title="{esc(k)}: {v}"></div>'
                   for k, v in items)
    return (f'<div class="chart reveal">{h2("bars", L["by_day"], "orange")}<div class="bars">{bars}</div>'
            f'<div class="axis"><span>{esc(items[0][0])}</span><span>{esc(items[-1][0])}</span></div></div>')


def ul(items, L):
    if not items:
        return f'<p class="mut">{esc(L["no_data"])}</p>'
    return '<ul class="list">' + "".join(f"<li>{esc(x)}</li>" for x in items) + "</ul>"


def themes(items, L):
    if not items:
        return f'<p class="mut">{esc(L["no_data"])}</p>'
    rows = []
    for t in items:
        share = f'<div class="share">{esc(t.get("share",""))}</div>'
        rows.append(f'<div class="theme">{share}<div><div class="t">{esc(t.get("theme"))}</div>'
                    f'<div class="d">{esc(t.get("detail"))}</div></div></div>')
    return "".join(rows)


def friction(items, L):
    if not items:
        return f'<p class="mut">{esc(L["no_fric"])}</p>'
    out = []
    for f in items:
        out.append(f'<div class="fr reveal"><div class="head">{ic("alert")}{esc(f.get("problem"))}</div>'
                   f'<div class="ev">{esc(f.get("evidence"))}</div>'
                   f'<div class="fix">{ic("check")}<div><b>{esc(L["fix"])}</b> {esc(f.get("fix"))}</div></div></div>')
    return "".join(out)


def build(stats, an, lang):
    L = LABELS.get(lang, LABELS["en"])
    t = stats.get("totals", {})
    sec = an.get("sections", {})
    period = an.get("period_label") or L["period"].format(n=stats.get("window_days", "?"))
    mpd = round(t.get("messages", 0) / max(1, stats.get("span", {}).get("active_days", 1)))
    stats_html = "".join([
        stat("message", t.get("messages", 0), L["st_msg"], "mint"),
        stat("layers", t.get("sessions", 0), L["st_ses"], "pink"),
        stat("calendar", stats.get("span", {}).get("active_days", 0), L["st_days"], "orange"),
        stat("terminal", t.get("tool_calls", 0), L["st_tool"], "coral"),
        stat("edit", t.get("edits", 0), L["st_edit"], "mint"),
        stat("file", t.get("files_touched", 0), L["st_file"], "pink"),
        stat_suf("cpu", t.get("out_tok", 0) / 1000, L["st_tok"], "k", "orange"),
        stat("gauge", mpd, L["st_mpd"], "coral"),
    ])
    tools = "".join(f'<span class="chip">{esc(k)} · <b>{v}</b></span>' for k, v in stats.get("tools", {}).items())
    langs = "".join(f'<span class="chip">{esc(k)} · <b>{v}</b></span>' for k, v in stats.get("languages", {}).items()) \
        or f'<span class="mut">{esc(L["no_edit"])}</span>'
    md = sec.get("claude_md_additions") or []
    md_block = "<pre>" + "\n".join(esc(x) for x in md) + "</pre>" if md else f'<p class="mut">{esc(L["no_sugg"])}</p>'
    foot = L["foot"].format(ts=esc(stats.get("generated_at")))

    return f"""<!doctype html><html lang="{lang}"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(L["title"])}</title><style>{CSS}</style></head><body><div class="wrap">
<div class="eyebrow">{ic("activity")} {esc(L["eyebrow"])}</div>
<h1>{esc(L["h1"])}</h1>
<p class="meta">{esc(period)} · {esc(L["agents"])}: <b>{esc(stats.get('agents'))}</b> · {esc(L["models"])}: <b>{esc(', '.join(stats.get('models', [])) or '?')}</b></p>

<div class="stats reveal">{stats_html}</div>

<div class="summary reveal"><div class="k">{ic("target")} {esc(L["summary_k"])}</div><p>{esc(an.get('summary'))}</p></div>

{per_day(stats.get('per_day', {}), L)}

<section class="reveal">{h2("layers", L["s_work"], "mint")}{themes(sec.get('what_you_work_on'), L)}</section>

<section class="reveal">{h2("activity", L["s_use"], "pink")}
<div class="label">{esc(L["tools"])}</div><div class="chips">{tools}</div>
<div class="label">{esc(L["langs"])}</div><div class="chips">{langs}</div>
{ul(sec.get('how_you_use'), L)}</section>

<section class="reveal">{h2("award", L["s_win"], "mint")}{ul(sec.get('impressive'), L)}</section>

<section>{h2("alert", L["s_fric"], "coral")}{friction(sec.get('friction'), L)}</section>

<section class="reveal">{h2("compass", L["s_feat"], "orange")}{ul(sec.get('features_to_try'), L)}</section>

<section class="reveal">{h2("filecode", L["s_md"], "pink")}{md_block}</section>

<section class="reveal">{h2("branch", L["s_new"], "mint")}{ul(sec.get('new_ways'), L)}</section>

<section class="reveal">{h2("trending", L["s_hor"], "orange")}<div class="horizon">{esc(sec.get('on_the_horizon'))}</div></section>

<div class="foot">{ic("cpu2")} {foot}</div>
</div><script>{JS}</script></body></html>"""


def main(argv):
    def arg(name, default=None):
        return argv[argv.index(name) + 1] if name in argv else default
    stats = json.load(open(os.path.expanduser(arg("--stats", "/tmp/mentor-stats.json")), encoding="utf-8"))
    ap = arg("--analysis")
    an = json.load(open(os.path.expanduser(ap), encoding="utf-8")) if ap and os.path.exists(os.path.expanduser(ap)) else {}
    lang = arg("--lang") or an.get("lang") or "en"
    out = os.path.expanduser(arg("--out", "~/.claude/usage-data/mentor-report.html"))
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(build(stats, an, lang))
    print(out)


if __name__ == "__main__":
    main(sys.argv)
